### PR TITLE
change term_type to vt100

### PR DESCRIPTION
**Pull request by Ali-aqrabawi**
**Description**

change the term_type to `vt100` instead of `Dump`, 

`vt100` is widely used in machines.

### CODE REVIEW

**Comment by selfuryon** [comment]
Hello, @Ali-aqrabawi 
I had some problems with Mikrotik when I used a `vt100` terminal type so I decided to use a `dumb` for simplicity. 
I need to test it again on Mikrotik but does this improvement help for something?

**Comment by Ali-aqrabawi** [comment]
i had same problem with nxos when `dumb` is used, but the problem is not always happening.

**Comment by selfuryon** [comment]
The problem in Mikrotik was escape sequences (the color for terminal) and clearing from it was painful. When I switched to the `dumb` term type I got the clear text without escape sequences. This was the main goal for switching to the `dumb`.
I hadn't any problems with any type of devices. But I haven't the real Nexus for testing this. If you find the reason for your problem, please write about it!

**Comment by Ali-aqrabawi** [comment]
i will close this pr, and discuss the term type in the code refactor, i will try to reproduce the issue with nexus and send you the debugs.

**Pull request closed without merging**
